### ISSUE TITLE
Automate wheel packaging on CI build workers

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/swmm-python#38]
Move wheel build from OWA/swmm repository to swmm-toolkit package.

**Comment by lrntct** [comment]
@michaeltryby In order to facilitate the maintenance of the CI infrastructure, I believe we should use only one CI provider for every architectures (Win, MacOS and Linux on x86), and prefereably, aarch64, which will become important with the Apple move to ARM.
I see two possibilities Azure pipelines or GitHub actions for the ability to run numerous parallel jobs (10 and 20). The latter advertise the support of arm64, but it is not clear if it available on the cloud.

Any thought?

**Comment by michaeltryby** [comment]
@lrntct Yes I agree using a single provider should help simplify maintenance. I have no experience with Azure. I have configured Appveyor, Travis, and Actions. Of the three I thought Actions was the best in terms of the quality of the documentation and ease of use. I especially liked that with Actions there are no third-party integration issues to worry about. 

I haven't thought through the Apple ARM issue, though I suppose we can configure our build to produce a universal binary when the time comes. 

So I guess my vote would be for using Actions.

**Comment by michaeltryby** [comment]
As an example, here is a [link](https://github.com/SWMM-Project/swmm-solver/blob/upstream-dev/.github/workflows/build-and-test.yml)to an Actions script I wrote for the main build/test CI for SWMM.

**Comment by lrntct** [comment]
@michaeltryby I have some experience with Azure (and Circle, Travis, AppVeyor and Bitbucket pipelines), and none with GH Actions. I am OK to try to setup Actions. The ability to easily store artifacts is a plus for GH Actions. In the end, most of the CI services work on the same principles, so I hope it should not be very difficult to get used to Actions.

**Comment by michaeltryby** [comment]
Closed in PR #45
