### ISSUE TITLE
Linux wheels are NOT manylinux compliant 

### ISSUE THREAD

**Issue by jennwuu** [OpenWaterAnalytics/swmm-python#59]
When I try to import solver from swmm-toolkit in linux, I get missing .dll file error.

```cmd
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyswmm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyswmm/__init__.py", line 11, in <module>
    from pyswmm.links import Link, Links
  File "/usr/local/lib/python3.6/dist-packages/pyswmm/links.py", line 12, in <module>
    from pyswmm.swmm5 import PYSWMMException
  File "/usr/local/lib/python3.6/dist-packages/pyswmm/swmm5.py", line 20, in <module>
    from swmm.toolkit import solver
  File "/usr/local/lib/python3.6/dist-packages/swmm/toolkit/solver.py", line 33, in <module>
    _solver = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/swmm/toolkit/solver.py", line 29, in swig_import_helper
    _mod = imp.load_module('_solver', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libswmm5.so: cannot open shared object file: No such file or directory
```

**Comment by michaeltryby** [comment]
This bug also manifests itself on the readthedocs server causing the documentation build to fail.

**Comment by michaeltryby** [comment]
We have determined that there is a problem with the Linux wheel build. As a work around Linux users are advised to build swmm-toolkit wheels from the source distribution. Be advised SWIG is required as a build dependency and that build and installing swmm-toolkit as an egg will not work.

**Comment by michaeltryby** [comment]
We are aware of this problem and working to make manylinux wheels part of the next swmm-toolkit release.

**Comment by michaeltryby** [comment]
I have been studying and thinking about this problem some and wanted to write it up here to help process the information and communicate with others. 

Our current wheel build is a little atypical. There aren't very many examples of SWIG wrap wheel builds in the wild to work from. Another thing unique about our build is that we link the SWIGed wrapper library to our swmm5 dynamic libraries. Studying the Python packaging documentation it is not immediately clear how best to package these library dependencies. Our current scikit-build setup treats them like "data" and applies python data packaging mechanisms. Everything works great! 

The problem arrises when we perform a "auditwheel repair" on the Linux wheels in preparation for distributing them on pypi. The purpose of auditwheel is to gather external dependencies and move them into the wheel so said dependencies are contained and available at runtime. Unfortunately, auditwheel was not designed with our use case in mind. It assumes that dependent libraries are external to the wheel. It collects them, creates a location for them in the wheel, and sets the paths accordingly. The problem is that this breaks the links that we set up to find our swmm libraries that are already internal -- located in the data portion of the wheel. 

So that is the problem in a nutshell. What are the potential solutions? Basically, we have three choices, 1) we can leave things how they currently are. Linux users can build the wheel from the source distribution; 2) we can refactor our wheel to conform with auditwheel's assumptions; or 3) we write custom scripts to perform these relocation tasks ourselves.
