### ISSUE TITLE
Higher Level OutputAPI

### ISSUE THREAD

**Issue by karosc** [OpenWaterAnalytics/swmm-python#82]
I have occasionally had a need for fast, programmatic access to the binary SWMM output files, and as a python lover have turned to modules written by [bemcdonnell](https://github.com/bemcdonnell/SWMMOutputAPI) or [timcera](https://timcera.bitbucket.io/swmmtoolbox/docsrc/index.html). 

However, lately I've been yearning for a more full fledged outputAPI package that integrates with the numpy/pandas ecosystem, takes care of the boilerplate parsing of output meta data to allow for a more object-oriented experience, and perhaps provides some statistical functionality as well. To my knowledge, there isn't really anything our there like that yet (is there?). I can see there was a solid attempt from the developers of the stale [SWMM python gui applicaiton](https://github.com/USEPA/SWMM-EPANET_User_Interface/blob/dev-ui-py3qt5/src/Externals/swmm/outputapi/SMOutputSWIG.py). But the file no longer integrates with the current swmm-python, and requires some overhaul. 

I really like the implementation of swmm-python because it uses C for very fast access to the binary file (orders of magnitude faster than the [pure python implementation](https://bitbucket.org/timcera/swmmtoolbox/src/master/src/swmmtoolbox/swmmtoolbox.py)), but the existing API is too low-level for my liking. I'd like to develop something new (probably inspired by what was developed for the SWMM gui), but I am not sure if it deserves it's own repo, or perhaps should be integrated with this one. Thoughts on this?

I think whatever I'd develop would be heavily dependent on the swmm toolkit output swig api provided by this library. How mature to feel the api is here? Do you see any major overhaul on the horizon? I don't want to develop anything based on an API that has incoming breaking changes.

I'd appreciate your thoughts on this idea.

Thanks!

**Comment by michaeltryby** [comment]
@karosc Great to hear from you!  Your thoughts are very serendipitous as several of us have come to the same conclusions as you have. To be fair, swmm-toolkit is low level by design and intended to facilitate the development of higher level more user friendly APIs. We have several things going on related to your idea. 

Pyswmm is an example of a higher level UI built on top of swmm-toolkit. @jennwuu has been working on a PR that adds swmm.output to pyswmm. 

Pandas supports hdf5 binary format and can import it directly into an DataFrame. @cbuahin has been working on extending swmm to support both original format and hdf5 format output files. This approach would eliminate the need for translating formats in versions of swmm going forward.  

Lastly, I am kicking around the idea of using the swmm.output to dump output data into a DataFrame to facilitate some QA work I'm doing. This could turn into a tool supporting older versions of swmm or something that supports swmm formats in pandas more generally along the lines of swmm-api and swmmio.  

The swmm-output API is stable and not likely to change very much. We are committed to maintaining backwards compatibility. If you are interested, you are welcome too plug in to any of these efforts. We are always looking for developers!

**Comment by jennwuu** [comment]
Thanks for summarizing! There is a PR for swmm output interaction in pyswmm. Feel free to check it out and make suggestions. Pyswmm output should be easy to convert to data frame.

**Comment by karosc** [comment]
Thanks for a great rundown @michaeltryby. I'm very interested to see where @cbuahin is developing the hdf5 format code (I couldn't easily find the repo if it is public). That format is also present in HEC-RAS/HMS modeling as well as in [the python implementation of HSPF](https://github.com/respec/HSPsquared), so I know others in the modeling space are familiar with it too. Providing that kind of output file might render this idea/effort somewhat obsolete. Do you think EPA would adopt that kind of functionality in the canonical model code if it were implemented?

Nevertheless, I still think there is value in having something for quickly processing older SWMM output files. @jennwuu, I like what you have done in your pyswmm fork. It provides an easy api to list out the links, nodes, etc. and makes it easy to pull output time series without having to fiddle with the shared_enum. I'll see if I can pull your fork into a virtual environment of my own and play around with it and possibly expand upon it. Ultimately I'd like to be able to rope in other functionality that goes beyond just pulling time series from an output file. I think at that point it might make more sense to fork out a new project. 

Thanks to you both for keeping SWMM an open model. I love the community development that goes on in this space, it makes SWMM one of my favorite models to work with.

**Comment by jennwuu** [comment]
@karosc Sounds good! Feel free to add any comments/suggestions in pyswmm PR. I did not include pandas, but you should be quickly to convert swmm output to dataframe using pd.DataFrame.from_dict functionality.

**Comment by karosc** [comment]
closing this to continue discussion #85
