### ISSUE TITLE
Pollutant treatment enhancements.

### ISSUE THREAD

**Issue by bemason** [OpenWaterAnalytics/swmm-python#92]
We made modifications to SWMM to allow more flexibility and options when running pollutant treatment and generation processes. Before we can modify pyswmm to enable this functionality, we need to modify swmm-python. This includes adding CIN, REACTORC, and HRT to shared_enum.py  and then the tests for these additions in test_solver.py.

**Comment by karosc** [comment]
I think this would also require updating the solver submodule to the latest develop branch of [SWMM](https://github.com/OpenWaterAnalytics/Stormwater-Management-Model). @michaeltryby, does that sound alright to you? I'd like to help here because I also have a minor addition to fix [subcatchment P_EVAP_RATE](https://github.com/karosc/swmm-python/blob/2c51f5825cca68fbf2da5749f13befeb16377b27/swmm-toolkit/src/swmm/toolkit/shared_enum.py#L324). However, I'm not so familiar with your improved treatment routines, so it might take me a while to put together a complete pull request.

**Comment by bemason** [comment]
Hi @karosc, we already made the pollutant changes to SWMM. See this pull request for more details: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/326. From my understanding after talking with @abhiramm7, the changes in that pull request were the only changes needed in SWMM to enable this functionality and now we need to make the changes to swmm-python, but I could be mistaken.

**Comment by karosc** [comment]
You are correct, your additions are present in the develop branch of SWMM. However, for swmm-python links to SWMM as a git [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules), pointing to a specific commit in the SWMM git tree. The [current submodule](https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/tree/93891ff1e3775073895a3b96f38fa6999e961ed9) points to a commit in history that predates your commits. So not only will you need to made changes to the shared_enum.py and test_solver.py files, but you will also need to update the submodule to point to the latest development branch of SWMM.

@michaeltryby mentioned updating this library with SWMM 5.1.14 in an [earlier issue](https://github.com/OpenWaterAnalytics/swmm-python/issues/87), but I'm not sure where that stands. If you make your python changes, update the submodule, and all tests pass, you should be good.

**Comment by karosc** [comment]
@michaeltryby, I tried to update the swmm-solver to the lastest commit in the develop branch of [SWMM](https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/tree/develop), but I think swig is not liking the changes you [made here](https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/commit/df8a378a19ad137e78a151df7bd936f017d64d75)

When I try to compile swmm-python using the latest SWMM branch, I get the following CMAKE error:

```[ 91%] Linking C executable runswmm
[ 91%] Built target runswmm
Scanning dependencies of target solver_swig_compilation
[ 92%] Swig compile solver.i for python
/mnt/SSD/swmm-python/swmm-toolkit/swmm-solver/src/solver/include/toolkit.h:35: Error: Syntax error in input(1).
gmake[2]: *** [src/swmm/toolkit/CMakeFiles/solver_swig_compilation.dir/build.make:83: src/swmm/toolkit/CMakeFiles/solver.dir/solverPYTHON.stamp] Error 1
gmake[2]: *** Deleting file 'src/swmm/toolkit/CMakeFiles/solver.dir/solverPYTHON.stamp'
gmake[1]: *** [CMakeFiles/Makefile2:327: src/swmm/toolkit/CMakeFiles/solver_swig_compilation.dir/all] Error 2
gmake: *** [Makefile:171: all] Error 2
Traceback (most recent call last):
  File "/home/karosc/miniconda3/envs/swmmpd/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 593, in setup
    cmkr.make(make_args, env=env)
  File "/home/karosc/miniconda3/envs/swmmpd/lib/python3.6/site-packages/skbuild/cmaker.py", line 515, in make
    os.path.abspath(CMAKE_BUILD_DIR())))

An error occurred while building with CMake.
  Command:
    cmake --build . --target install --config Release --
  Source directory:
    /mnt/SSD/swmm-python/swmm-toolkit
  Working directory:
    /mnt/SSD/swmm-python/swmm-toolkit/_skbuild/linux-x86_64-3.6/cmake-build
Please see CMake's output for more information.
```

I am too green to monkey around with the swig interface files without direction, thoughts on where the issue lies?

**Comment by michaeltryby** [comment]
Hey @karosc, sorry about being incommunicado. Are you getting the error when you build locally? What system / compiler are you using?

**Comment by karosc** [comment]
I was able to resolve the issue last night by defining EXPORT_TOOLKIT in the swig interface file. See #94, which I just now created.

**Comment by abhiramm7** [comment]
Addressed in https://github.com/OpenWaterAnalytics/swmm-python/pull/94
